# Form implementation generated from reading ui file 'C:\Users\DANIEL\Documents\GitHub\UI\tokenResultado.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 284)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tblTokens = QtWidgets.QTableWidget(parent=Dialog)
        self.tblTokens.setObjectName("tblTokens")
        self.tblTokens.setColumnCount(0)
        self.tblTokens.setRowCount(0)
        self.horizontalLayout.addWidget(self.tblTokens)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
